pipeline{
     agent any
        stages {
           stage ('build_stage'){
              steps{
                 sh 'echo "Hello build stage is running on the `hostname` host!"'
              } 
            stage ('Test_stage'){
              steps{
                sh 'echo "Hello test stage is running on the `hostname` host!"'
              }
             }
           }
        }
}
