pipeline{
     agent any
          stages{
            steps('build'){
             sh 'echo "This build stage from `hostname` host"'
            }
          
          }
          steps{
           sh 'echo "This is Test stage from `hostname` host"'
          }

}
