peline{
    agent any
    stages {
      stage('build_app') {
        steps {
          sh 'echo "This is build stage running on the `hostname` host!" '
        }
       parallel {
         stage('build_app') {
           steps {
             sh 'echo "This is build stage running on the `hostname` host!"'
           }
         }
        stage('build1.1`){
          steps{
            sh 'sleep 5 && echo "parallel step1.1"
          }  
        }   
        stage('build1.2'){ 
         steps{
           sh 'sleep 5 && echo "parallel step 1.2"
         }
        }
       }
      }
    }

}
